//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandyWork.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandyWork.Localization.LocalizedResource", typeof(LocalizedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ALL 的本地化字符串。
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE 的本地化字符串。
        /// </summary>
        public static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DELETE 的本地化字符串。
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DROP_DOWN_LIST_OPTION_LABEL 的本地化字符串。
        /// </summary>
        public static string DROP_DOWN_LIST_OPTION_LABEL {
            get {
                return ResourceManager.GetString("DROP_DOWN_LIST_OPTION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EDIT 的本地化字符串。
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FAILED 的本地化字符串。
        /// </summary>
        public static string FAILED {
            get {
                return ResourceManager.GetString("FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOADING 的本地化字符串。
        /// </summary>
        public static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSG_COMMON_ERROR_TIP 的本地化字符串。
        /// </summary>
        public static string MSG_COMMON_ERROR_TIP {
            get {
                return ResourceManager.GetString("MSG_COMMON_ERROR_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NAME 的本地化字符串。
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NO 的本地化字符串。
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NOTEXIST_USERNAME 的本地化字符串。
        /// </summary>
        public static string NOTEXIST_USERNAME {
            get {
                return ResourceManager.GetString("NOTEXIST_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PERMISSION 的本地化字符串。
        /// </summary>
        public static string PERMISSION {
            get {
                return ResourceManager.GetString("PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QUERY 的本地化字符串。
        /// </summary>
        public static string QUERY {
            get {
                return ResourceManager.GetString("QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RESET 的本地化字符串。
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ROLE 的本地化字符串。
        /// </summary>
        public static string ROLE {
            get {
                return ResourceManager.GetString("ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SUCCEED 的本地化字符串。
        /// </summary>
        public static string SUCCEED {
            get {
                return ResourceManager.GetString("SUCCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USER 的本地化字符串。
        /// </summary>
        public static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YES 的本地化字符串。
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
