//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandyWork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataHistory
    {
        public string Id { get; set; }
        public string CreatedById { get; set; }
        public string LastModifiedById { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public string Category { get; set; }
        public string ForeignId { get; set; }
        public string Description { get; set; }
        public string Keep1 { get; set; }
        public string Keep2 { get; set; }
        public string Keep3 { get; set; }
        public string Keep4 { get; set; }
        public string Keep5 { get; set; }
        public string Keep6 { get; set; }
        public string Keep7 { get; set; }
        public string Keep8 { get; set; }
        public string Keep9 { get; set; }
        public string Keep10 { get; set; }
        public string Keep11 { get; set; }
        public string Keep12 { get; set; }
        public string Keep13 { get; set; }
        public string Keep14 { get; set; }
        public string Keep15 { get; set; }
    }
}
