namespace HandyWork.Model.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class varchar2nvarchar : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.AuthRolePermission", "PermissionId", "dbo.AuthPermission");
            DropForeignKey("dbo.AuthUserPermission", "PermissionId", "dbo.AuthPermission");
            DropForeignKey("dbo.AuthUserRole", "RoleId", "dbo.AuthRole");
            DropForeignKey("dbo.AuthRolePermission", "RoleId", "dbo.AuthRole");
            DropForeignKey("dbo.AuthUserRole", "UserId", "dbo.User");
            DropForeignKey("dbo.AuthUserPermission", "UserId", "dbo.User");
            DropIndex("dbo.AuthUserRole", new[] { "RoleId" });
            DropIndex("dbo.AuthUserRole", new[] { "UserId" });
            DropIndex("dbo.AuthRolePermission", new[] { "PermissionId" });
            DropIndex("dbo.AuthRolePermission", new[] { "RoleId" });
            DropIndex("dbo.AuthUserPermission", new[] { "PermissionId" });
            DropIndex("dbo.AuthUserPermission", new[] { "UserId" });
            DropPrimaryKey("dbo.AuthPermission");
            DropPrimaryKey("dbo.AuthRole");
            DropPrimaryKey("dbo.User");
            DropPrimaryKey("dbo.DataHistory");
            DropPrimaryKey("dbo.AuthRolePermission");
            DropPrimaryKey("dbo.AuthUserPermission");
            DropPrimaryKey("dbo.AuthUserRole");
            AddColumn("dbo.AppConfiguration", "AppValue", c => c.String());
            AlterColumn("dbo.AppConfiguration", "AppCategory", c => c.String(maxLength: 50));
            AlterColumn("dbo.AppConfiguration", "Keep1", c => c.String(maxLength: 500));
            AlterColumn("dbo.AppConfiguration", "Keep2", c => c.String(maxLength: 500));
            AlterColumn("dbo.AppConfiguration", "Keep3", c => c.String(maxLength: 500));
            AlterColumn("dbo.AppConfiguration", "Keep4", c => c.String(maxLength: 500));
            AlterColumn("dbo.AppConfiguration", "Keep5", c => c.String(maxLength: 500));
            AlterColumn("dbo.AppConfiguration", "Keep6", c => c.String(maxLength: 500));
            AlterColumn("dbo.AppConfiguration", "Keep7", c => c.String(maxLength: 500));
            AlterColumn("dbo.AppConfiguration", "Keep8", c => c.String(maxLength: 500));
            AlterColumn("dbo.AppConfiguration", "Keep9", c => c.String(maxLength: 500));
            AlterColumn("dbo.AppConfiguration", "Keep10", c => c.String(maxLength: 500));
            AlterColumn("dbo.AppConfiguration", "Keep11", c => c.String(maxLength: 500));
            AlterColumn("dbo.AppConfiguration", "Description", c => c.String(maxLength: 200));
            AlterColumn("dbo.AuthPermission", "Id", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.AuthPermission", "Code", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.AuthPermission", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.AuthPermission", "Description", c => c.String(maxLength: 500));
            AlterColumn("dbo.AuthPermission", "CreatedById", c => c.String(maxLength: 40));
            AlterColumn("dbo.AuthPermission", "LastModifiedById", c => c.String(maxLength: 40));
            AlterColumn("dbo.AuthRole", "Id", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.AuthRole", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.AuthRole", "Description", c => c.String(maxLength: 500));
            AlterColumn("dbo.AuthRole", "CreatedById", c => c.String(maxLength: 40));
            AlterColumn("dbo.AuthRole", "LastModifiedById", c => c.String(maxLength: 40));
            AlterColumn("dbo.User", "Id", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.User", "RealName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.User", "UserName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.User", "Password", c => c.String(maxLength: 50));
            AlterColumn("dbo.User", "Phone", c => c.String(maxLength: 250));
            AlterColumn("dbo.User", "Email", c => c.String(maxLength: 256));
            AlterColumn("dbo.User", "CreatedById", c => c.String(maxLength: 40));
            AlterColumn("dbo.User", "LastModifiedById", c => c.String(maxLength: 40));
            AlterColumn("dbo.DataHistory", "Id", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.DataHistory", "CreatedById", c => c.String(maxLength: 40));
            AlterColumn("dbo.DataHistory", "LastModifiedById", c => c.String(maxLength: 40));
            AlterColumn("dbo.DataHistory", "Category", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.DataHistory", "ForeignId", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.DataHistory", "Description", c => c.String());
            AlterColumn("dbo.DataHistory", "Keep1", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep2", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep3", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep4", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep5", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep6", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep7", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep8", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep9", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep10", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep11", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep12", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep13", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep14", c => c.String(maxLength: 500));
            AlterColumn("dbo.DataHistory", "Keep15", c => c.String(maxLength: 500));
            AlterColumn("dbo.AuthRolePermission", "PermissionId", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.AuthRolePermission", "RoleId", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.AuthUserPermission", "PermissionId", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.AuthUserPermission", "UserId", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.AuthUserRole", "RoleId", c => c.String(nullable: false, maxLength: 40));
            AlterColumn("dbo.AuthUserRole", "UserId", c => c.String(nullable: false, maxLength: 40));
            AddPrimaryKey("dbo.AuthPermission", "Id");
            AddPrimaryKey("dbo.AuthRole", "Id");
            AddPrimaryKey("dbo.User", "Id");
            AddPrimaryKey("dbo.DataHistory", "Id");
            AddPrimaryKey("dbo.AuthRolePermission", new[] { "PermissionId", "RoleId" });
            AddPrimaryKey("dbo.AuthUserPermission", new[] { "PermissionId", "UserId" });
            AddPrimaryKey("dbo.AuthUserRole", new[] { "RoleId", "UserId" });
            CreateIndex("dbo.AuthUserRole", "RoleId");
            CreateIndex("dbo.AuthUserRole", "UserId");
            CreateIndex("dbo.AuthRolePermission", "PermissionId");
            CreateIndex("dbo.AuthRolePermission", "RoleId");
            CreateIndex("dbo.AuthUserPermission", "PermissionId");
            CreateIndex("dbo.AuthUserPermission", "UserId");
            AddForeignKey("dbo.AuthRolePermission", "PermissionId", "dbo.AuthPermission", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AuthUserPermission", "PermissionId", "dbo.AuthPermission", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AuthUserRole", "RoleId", "dbo.AuthRole", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AuthRolePermission", "RoleId", "dbo.AuthRole", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AuthUserRole", "UserId", "dbo.User", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AuthUserPermission", "UserId", "dbo.User", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.AuthUserPermission", "UserId", "dbo.User");
            DropForeignKey("dbo.AuthUserRole", "UserId", "dbo.User");
            DropForeignKey("dbo.AuthRolePermission", "RoleId", "dbo.AuthRole");
            DropForeignKey("dbo.AuthUserRole", "RoleId", "dbo.AuthRole");
            DropForeignKey("dbo.AuthUserPermission", "PermissionId", "dbo.AuthPermission");
            DropForeignKey("dbo.AuthRolePermission", "PermissionId", "dbo.AuthPermission");
            DropIndex("dbo.AuthUserPermission", new[] { "UserId" });
            DropIndex("dbo.AuthUserPermission", new[] { "PermissionId" });
            DropIndex("dbo.AuthRolePermission", new[] { "RoleId" });
            DropIndex("dbo.AuthRolePermission", new[] { "PermissionId" });
            DropIndex("dbo.AuthUserRole", new[] { "UserId" });
            DropIndex("dbo.AuthUserRole", new[] { "RoleId" });
            DropPrimaryKey("dbo.AuthUserRole");
            DropPrimaryKey("dbo.AuthUserPermission");
            DropPrimaryKey("dbo.AuthRolePermission");
            DropPrimaryKey("dbo.DataHistory");
            DropPrimaryKey("dbo.User");
            DropPrimaryKey("dbo.AuthRole");
            DropPrimaryKey("dbo.AuthPermission");
            AlterColumn("dbo.AuthUserRole", "UserId", c => c.String(nullable: false, maxLength: 40, unicode: false));
            AlterColumn("dbo.AuthUserRole", "RoleId", c => c.String(nullable: false, maxLength: 40, unicode: false));
            AlterColumn("dbo.AuthUserPermission", "UserId", c => c.String(nullable: false, maxLength: 40, unicode: false));
            AlterColumn("dbo.AuthUserPermission", "PermissionId", c => c.String(nullable: false, maxLength: 40, unicode: false));
            AlterColumn("dbo.AuthRolePermission", "RoleId", c => c.String(nullable: false, maxLength: 40, unicode: false));
            AlterColumn("dbo.AuthRolePermission", "PermissionId", c => c.String(nullable: false, maxLength: 40, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep15", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep14", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep13", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep12", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep11", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep10", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep9", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep8", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep7", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep6", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep5", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep4", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep3", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep2", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Keep1", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.DataHistory", "Description", c => c.String(maxLength: 5000, unicode: false));
            AlterColumn("dbo.DataHistory", "ForeignId", c => c.String(nullable: false, maxLength: 40, unicode: false));
            AlterColumn("dbo.DataHistory", "Category", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.DataHistory", "LastModifiedById", c => c.String(maxLength: 40, unicode: false));
            AlterColumn("dbo.DataHistory", "CreatedById", c => c.String(maxLength: 40, unicode: false));
            AlterColumn("dbo.DataHistory", "Id", c => c.String(nullable: false, maxLength: 40, unicode: false));
            AlterColumn("dbo.User", "LastModifiedById", c => c.String(maxLength: 40, unicode: false));
            AlterColumn("dbo.User", "CreatedById", c => c.String(maxLength: 40, unicode: false));
            AlterColumn("dbo.User", "Email", c => c.String(maxLength: 256, unicode: false));
            AlterColumn("dbo.User", "Phone", c => c.String(maxLength: 250, unicode: false));
            AlterColumn("dbo.User", "Password", c => c.String(maxLength: 50, unicode: false));
            AlterColumn("dbo.User", "UserName", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.User", "RealName", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.User", "Id", c => c.String(nullable: false, maxLength: 40, unicode: false));
            AlterColumn("dbo.AuthRole", "LastModifiedById", c => c.String(maxLength: 40, unicode: false));
            AlterColumn("dbo.AuthRole", "CreatedById", c => c.String(maxLength: 40, unicode: false));
            AlterColumn("dbo.AuthRole", "Description", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.AuthRole", "Name", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.AuthRole", "Id", c => c.String(nullable: false, maxLength: 40, unicode: false));
            AlterColumn("dbo.AuthPermission", "LastModifiedById", c => c.String(maxLength: 40, unicode: false));
            AlterColumn("dbo.AuthPermission", "CreatedById", c => c.String(maxLength: 40, unicode: false));
            AlterColumn("dbo.AuthPermission", "Description", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.AuthPermission", "Name", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.AuthPermission", "Code", c => c.String(nullable: false, maxLength: 50, unicode: false));
            AlterColumn("dbo.AuthPermission", "Id", c => c.String(nullable: false, maxLength: 40, unicode: false));
            AlterColumn("dbo.AppConfiguration", "Description", c => c.String(maxLength: 200, unicode: false));
            AlterColumn("dbo.AppConfiguration", "Keep11", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.AppConfiguration", "Keep10", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.AppConfiguration", "Keep9", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.AppConfiguration", "Keep8", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.AppConfiguration", "Keep7", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.AppConfiguration", "Keep6", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.AppConfiguration", "Keep5", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.AppConfiguration", "Keep4", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.AppConfiguration", "Keep3", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.AppConfiguration", "Keep2", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.AppConfiguration", "Keep1", c => c.String(maxLength: 500, unicode: false));
            AlterColumn("dbo.AppConfiguration", "AppCategory", c => c.String(maxLength: 50, unicode: false));
            DropColumn("dbo.AppConfiguration", "AppValue");
            AddPrimaryKey("dbo.AuthUserRole", new[] { "RoleId", "UserId" });
            AddPrimaryKey("dbo.AuthUserPermission", new[] { "PermissionId", "UserId" });
            AddPrimaryKey("dbo.AuthRolePermission", new[] { "PermissionId", "RoleId" });
            AddPrimaryKey("dbo.DataHistory", "Id");
            AddPrimaryKey("dbo.User", "Id");
            AddPrimaryKey("dbo.AuthRole", "Id");
            AddPrimaryKey("dbo.AuthPermission", "Id");
            CreateIndex("dbo.AuthUserPermission", "UserId");
            CreateIndex("dbo.AuthUserPermission", "PermissionId");
            CreateIndex("dbo.AuthRolePermission", "RoleId");
            CreateIndex("dbo.AuthRolePermission", "PermissionId");
            CreateIndex("dbo.AuthUserRole", "UserId");
            CreateIndex("dbo.AuthUserRole", "RoleId");
            AddForeignKey("dbo.AuthUserPermission", "UserId", "dbo.User", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AuthUserRole", "UserId", "dbo.User", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AuthRolePermission", "RoleId", "dbo.AuthRole", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AuthUserRole", "RoleId", "dbo.AuthRole", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AuthUserPermission", "PermissionId", "dbo.AuthPermission", "Id", cascadeDelete: true);
            AddForeignKey("dbo.AuthRolePermission", "PermissionId", "dbo.AuthPermission", "Id", cascadeDelete: true);
        }
    }
}
